spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route_qq
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
        - id: member
          uri: lb://member
          predicates:
            - Path=/member/**
    nacos:
      discovery:
        server-addr: @nacos.ip@:@nacos.port@
server:
  port: 8888
